# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MetisQgisAppDialog
                                 A QGIS plugin
 Metis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-01
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Raize by Joel PINHO
        email                : raizetvision@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'metis_qgis_app_dialog_base.ui'))

FORM_CLASS_LOADING, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'metis_loading_dialog_base.ui'))

FORM_CLASS_APDGC, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'metis_apdgc_dialog_base.ui'))

FORM_CLASS_LAYERS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'metis_layers_dialog_base.ui'))

FORM_CLASS_DOE, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'metis_doe_dialog_base.ui'))

FORM_CLASS_APD, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'metis_apd_dialog_base.ui'))

class MetisQgisAppDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(MetisQgisAppDialog, self).__init__(parent)
        self.setupUi(self)

class MetisQgisLoadingDialog(QtWidgets.QDialog, FORM_CLASS_LOADING):
    def __init__(self, parent=None):
        """Constructor."""
        super(MetisQgisLoadingDialog, self).__init__(parent)
        self.setupUi(self)

class MetisQgisApdgcDialog(QtWidgets.QDialog, FORM_CLASS_APDGC):
    def __init__(self, parent=None):
        """Constructor."""
        super(MetisQgisApdgcDialog, self).__init__(parent)
        self.setupUi(self)

class MetisQgisLayersDialog(QtWidgets.QDialog, FORM_CLASS_LAYERS):
    def __init__(self, parent=None):
        """Constructor."""
        super(MetisQgisLayersDialog, self).__init__(parent)
        self.setupUi(self)

class MetisQgisDoeDialog(QtWidgets.QDialog, FORM_CLASS_DOE):
    def __init__(self, parent=None):
        """Constructor."""
        super(MetisQgisDoeDialog, self).__init__(parent)
        self.setupUi(self)

class MetisQgisApdDialog(QtWidgets.QMainWindow, FORM_CLASS_APD):
    def __init__(self, parent=None):
        """Constructor."""
        super(MetisQgisApdDialog, self).__init__(parent)
        self.setupUi(self)