# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'metis_apdgc_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Metis_Apdgc_Dialog(object):
    def setupUi(self, Metis_Apdgc_Dialog):
        Metis_Apdgc_Dialog.setObjectName("Metis_Apdgc_Dialog")
        Metis_Apdgc_Dialog.resize(690, 479)
        self.lineEditSroname = QtWidgets.QLineEdit(Metis_Apdgc_Dialog)
        self.lineEditSroname.setGeometry(QtCore.QRect(10, 100, 211, 25))
        self.lineEditSroname.setInputMask("")
        self.lineEditSroname.setObjectName("lineEditSroname")
        self.labelSroname = QtWidgets.QLabel(Metis_Apdgc_Dialog)
        self.labelSroname.setGeometry(QtCore.QRect(10, 70, 67, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSroname.setFont(font)
        self.labelSroname.setObjectName("labelSroname")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Metis_Apdgc_Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 691, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_apdgc_maintitle = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_apdgc_maintitle.setFont(font)
        self.label_apdgc_maintitle.setObjectName("label_apdgc_maintitle")
        self.horizontalLayout.addWidget(self.label_apdgc_maintitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.labelPhase = QtWidgets.QLabel(Metis_Apdgc_Dialog)
        self.labelPhase.setGeometry(QtCore.QRect(10, 140, 67, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelPhase.setFont(font)
        self.labelPhase.setObjectName("labelPhase")
        self.comboBoxPhase = QtWidgets.QComboBox(Metis_Apdgc_Dialog)
        self.comboBoxPhase.setGeometry(QtCore.QRect(10, 170, 211, 25))
        self.comboBoxPhase.setEditable(False)
        self.comboBoxPhase.setCurrentText("")
        self.comboBoxPhase.setObjectName("comboBoxPhase")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Metis_Apdgc_Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 430, 661, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonGenerateLayout = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonGenerateLayout.setObjectName("pushButtonGenerateLayout")
        self.horizontalLayout_2.addWidget(self.pushButtonGenerateLayout)
        self.labelCity = QtWidgets.QLabel(Metis_Apdgc_Dialog)
        self.labelCity.setGeometry(QtCore.QRect(10, 210, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelCity.setFont(font)
        self.labelCity.setObjectName("labelCity")
        self.lineEditCity = QtWidgets.QLineEdit(Metis_Apdgc_Dialog)
        self.lineEditCity.setGeometry(QtCore.QRect(10, 240, 211, 25))
        self.lineEditCity.setInputMask("")
        self.lineEditCity.setObjectName("lineEditCity")
        self.labelZipcode = QtWidgets.QLabel(Metis_Apdgc_Dialog)
        self.labelZipcode.setGeometry(QtCore.QRect(10, 280, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelZipcode.setFont(font)
        self.labelZipcode.setObjectName("labelZipcode")
        self.lineEditZipcode = QtWidgets.QLineEdit(Metis_Apdgc_Dialog)
        self.lineEditZipcode.setGeometry(QtCore.QRect(10, 310, 211, 25))
        self.lineEditZipcode.setInputMask("")
        self.lineEditZipcode.setObjectName("lineEditZipcode")
        self.labelInseecode = QtWidgets.QLabel(Metis_Apdgc_Dialog)
        self.labelInseecode.setGeometry(QtCore.QRect(10, 350, 81, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelInseecode.setFont(font)
        self.labelInseecode.setObjectName("labelInseecode")
        self.lineEditInseecode = QtWidgets.QLineEdit(Metis_Apdgc_Dialog)
        self.lineEditInseecode.setGeometry(QtCore.QRect(10, 380, 211, 25))
        self.lineEditInseecode.setInputMask("")
        self.lineEditInseecode.setObjectName("lineEditInseecode")

        self.retranslateUi(Metis_Apdgc_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Metis_Apdgc_Dialog)

    def retranslateUi(self, Metis_Apdgc_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Metis_Apdgc_Dialog.setWindowTitle(_translate("Metis_Apdgc_Dialog", "Dialog"))
        self.lineEditSroname.setPlaceholderText(_translate("Metis_Apdgc_Dialog", "VDLF-SROXX00"))
        self.labelSroname.setText(_translate("Metis_Apdgc_Dialog", "Projet"))
        self.label_apdgc_maintitle.setText(_translate("Metis_Apdgc_Dialog", "Paramètres DTP GC"))
        self.labelPhase.setText(_translate("Metis_Apdgc_Dialog", "Phase"))
        self.pushButtonCancel.setText(_translate("Metis_Apdgc_Dialog", "Annuler"))
        self.pushButtonGenerateLayout.setText(_translate("Metis_Apdgc_Dialog", "Genérer"))
        self.labelCity.setText(_translate("Metis_Apdgc_Dialog", "Commune"))
        self.lineEditCity.setPlaceholderText(_translate("Metis_Apdgc_Dialog", "Ex. Chinon"))
        self.labelZipcode.setText(_translate("Metis_Apdgc_Dialog", "Code postal"))
        self.lineEditZipcode.setPlaceholderText(_translate("Metis_Apdgc_Dialog", "Ex. 37500"))
        self.labelInseecode.setText(_translate("Metis_Apdgc_Dialog", "Code insee"))
        self.lineEditInseecode.setPlaceholderText(_translate("Metis_Apdgc_Dialog", "Ex. 37072"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Metis_Apdgc_Dialog = QtWidgets.QDialog()
    ui = Ui_Metis_Apdgc_Dialog()
    ui.setupUi(Metis_Apdgc_Dialog)
    Metis_Apdgc_Dialog.show()
    sys.exit(app.exec_())
